name: Quest
version: 1.0.1
main: com.narohid.quest.Quest
api-version: '1.20'

commands:
  quest:
    description: Main command for the Quest plugin.
    usage: /quest [help|cancel]
    permission: quest.use
    permission-message: "You don't have permission to use this command."
    aliases: [quests]
  questadmin:
    description: Administration command for the Quest plugin.
    usage: /questadmin <update|reload>
    permission: quest.admin
    permission-message: "You don't have permission to use this command."

permissions:
  quest.use:
    description: Permission to use the /quest command.
    default: true
  quest.admin:
    description: Permission to use the administration commands of Quest.
    default: op

authors:
  - Hid33n

depend: [PlaceholderAPI]
